//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblDailyNote
    {
        public string brcode { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime cmdate { get; set; }
        public string memono { get; set; }
        public string saletype { get; set; }
        public Nullable<decimal> Vno { get; set; }
        public Nullable<decimal> cash { get; set; }
        public Nullable<decimal> dd { get; set; }
        public Nullable<decimal> cc { get; set; }
        public Nullable<decimal> customer { get; set; }
        public Nullable<decimal> gv { get; set; }
        public Nullable<decimal> upi { get; set; }
        public string description { get; set; }
        public Nullable<decimal> totamount { get; set; }
        public Nullable<decimal> vno_credit { get; set; }
        public string description_credit { get; set; }
        public Nullable<decimal> cash_credit { get; set; }
        public Nullable<decimal> chq_credit { get; set; }
        public Nullable<decimal> totamount_credit { get; set; }
        public long ID { get; set; }
    }

    public class DNDataModel
    {
        [DataType(DataType.Date)]
        public System.DateTime cmdate { get; set; }
        public List<SelectListItem> GetBranches { get; set; }
        public List<tblDailyNote> Branches { get; set; }
    }
}
